### TODO#12
### Completa los ... de las siguientes peticiones por orden,
### para probar el API con el plugin REST CLIENT de VsCode

### Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@email.com",
  "password": "aaaaaaA1",
  "role": "USER"
}

###

### Login
POST http://localhost:8080/api/users/me/session
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "aaaaaaA1"
}

###

### Profile
GET http://localhost:8080/api/users/me
Cookie: session=<pon-aquí-el-session-id>
